Основы JS. Примитивные типы данных (решение задач)
js-tasks-ru/js-20220905_ilya724 pull request #2
Opened 2022-09-11 20:30 UTC by Shnyamsky

2022-09-11 20:31 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-12 16:37 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    console.error('sort type is incorrect');
👍 good лайк за вывод ошибки

2022-09-12 16:38 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'desc') return sortedArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-12 16:38 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const newObj = Object.fromEntries(
good 👍

2022-09-12 16:38 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const newObj = Object.fromEntries(
good 👍

2022-09-12 16:38 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-09-12 17:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-13 17:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-13 20:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-14 21:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const keys = path.split('.');
👍 good  лайк за использование замыкания

2022-09-14 21:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (let value of keys) {
`const value`

2022-09-14 21:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-09-14 21:32 UTC, dosandk approved these changes
good 👍
хорошие решения

2022-09-14 21:33 UTC, merged